# syntax=docker/dockerfile:1

# Builder image. It builds the venv that will be copied to the final image
FROM python:3.13-alpine3.21 AS builder

RUN set -x \
    && apk add --no-cache \
        ca-certificates \
        jemalloc \
        tzdata \
        dnscache \
        cifs-utils \
        libnfs \
        openssl-dev \
        snapcast

# Get static ffmpeg builds from https://hub.docker.com/r/mwader/static-ffmpeg/
COPY --from=mwader/static-ffmpeg:7.1.1 /ffmpeg /usr/local/bin/
COPY --from=mwader/static-ffmpeg:7.1.1 /ffprobe /usr/local/bin/

# Copy widevine client files to container
RUN mkdir -p /usr/local/bin/widevine_cdm
COPY widevine_cdm/* /usr/local/bin/widevine_cdm/

# JEMalloc for more efficient memory management
ENV LD_PRELOAD="/usr/lib/libjemalloc.so.2"

# Install UV for faster package management
RUN pip install uv

ADD dist dist
COPY requirements_all.txt .

# create venv which will be copied to the final image
ENV VIRTUAL_ENV=/app/venv
RUN uv venv $VIRTUAL_ENV

# pre-install ALL requirements into the venv
RUN uv pip install \
    --find-links "https://wheels.home-assistant.io/musllinux/" \
    -r requirements_all.txt

# Install Music Assistant from prebuilt wheel
ARG MASS_VERSION=2.5.5
RUN uv pip install \
    --no-cache \
    --find-links "https://wheels.home-assistant.io/musllinux/" \
    "music-assistant@dist/music_assistant-${MASS_VERSION}-py3-none-any.whl"

# we need to set (very permissive) permissions to the workdir
# and /tmp to allow running the container as non-root
RUN chmod -R 777 /app

##################################################################################################

# FINAL docker image for music assistant server

FROM python:3.13-alpine3.21

RUN set -x \
    && apk add --no-cache \
        ca-certificates \
        jemalloc \
        tzdata \
        dnscache \
        cifs-utils \
        libnfs \
        openssl-dev \
        snapcast

# Get static ffmpeg builds from https://hub.docker.com/r/mwader/static-ffmpeg/
COPY --from=mwader/static-ffmpeg:7.1.1 /ffmpeg /usr/local/bin/
COPY --from=mwader/static-ffmpeg:7.1.1 /ffprobe /usr/local/bin/

# Copy widevine client files to container
RUN mkdir -p /usr/local/bin/widevine_cdm
COPY widevine_cdm/* /usr/local/bin/widevine_cdm/

# JEMalloc for more efficient memory management
ENV LD_PRELOAD="/usr/lib/libjemalloc.so.2"

ENV VIRTUAL_ENV=/app/venv
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# copy the already build /app dir
COPY --from=builder /app /app

# the /app contents have correct permissions but for some reason /app itself does not.
# so apply again, but ONLY to the dir (otherwise we increase the size)
RUN chmod 777 /app

# Set some labels
ARG MASS_VERSION=2.5.5
ARG TARGETPLATFORM
LABEL \
    org.opencontainers.image.title="Music Assistant Server ZING" \
    org.opencontainers.image.description="Music Assistant is a free, opensource Media library manager that connects to your streaming services and a wide range of connected speakers. The server is the beating heart, the core of Music Assistant and must run on an always-on device like a Raspberry Pi, a NAS or an Intel NUC or alike." \
    org.opencontainers.image.source="https://github.com/music-assistant/server" \
    org.opencontainers.image.authors="The Music Assistant Team" \
    org.opencontainers.image.documentation="https://music-assistant.io" \
    org.opencontainers.image.licenses="Apache License 2.0" \
    io.hass.version="${MASS_VERSION}" \
    io.hass.type="addon" \
    io.hass.name="Music Assistant Server ZING" \
    io.hass.description="Music Assistant Server ZING" \
    io.hass.platform="${TARGETPLATFORM}" \
    io.hass.type="addon"

VOLUME [ "/data" ]
EXPOSE 8095

WORKDIR $VIRTUAL_ENV

ENTRYPOINT ["mass", "--config", "/data"] 